### ISSUE TITLE
0-7_LoginExperience

### ISSUE THREAD

**Issue by Spoondogg** [Spoondogg/ICARUS#119]
**User Registration / Authentication**
The entire Sign In, validation and OAuth experience is terrible.  Buttons should be easy to access and the user shouldn't feel like they're being thrown around just to get into the site.  OAuth redirects should retain the same look and feel of a MAIN Container as well as any outbound emails (ie: 

**ExternalLogin**
- [x] ExternalLogin.cshtml
  - [x] Create MAIN.externalLogin()

**ExternalLoginConfirmation**
*It's quite possible that this flow is no longer needed*
- [x] ExternalLoginConfirmation.cshtml
  - [x] Retain MAIN look and feel
  - [x] Unify with an init.js
  - [x] Refactor registration form

**ConfirmEmail**
- [x] ConfirmEmail.cshtml
  - [x] Unify with an init.js that
  - [x] Redirect the user to the application
  - [x] Launch MAIN.login()
- [x] ForgotPassword
- [x] ResetPassword

**TODO:**
- [x] Provide meaningful errors and warnings

**BugFix**
- [x] Hide label on INPUT[type='hidden']
